atp:
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    pooling: 'mean'
    response_only: true
    verbose: false
    log: false
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    pooling: 'min'
    response_only: false
    verbose: false
    log: false
lc:
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    llm_layers: "23"
    attention_threshold: 0.05
    verbose: false
    log: false
  -
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    llm_layers: "27"
    attention_threshold: 0.05
    verbose: false
    log: false
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    llm_layers: "31"
    attention_threshold: 0.05
    verbose: false
    log: false
lc++:
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    llm_layers: "23"
    attention_threshold: 0.05
    C: 10
    balance: false
    verbose: false
    log: false
  -
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    llm_layers: "27"
    attention_threshold: 0.05
    C: 0.01
    balance: false
    verbose: false
    log: false
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    llm_layers: "31"
    attention_threshold: 0.05
    C: 0.01
    balance: false
    verbose: false
    log: false
lapeig:
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    attention_threshold: 0.05
    topk: 7
    verbose: false
    log: false
act:
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    llm_layers: '24'
    C: 0.01
    pooling: '-1'
    balance: false
    checkpoint: false
    verbose: false
    log: false
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    llm_layers: '28'
    C: 0.01
    pooling: '-1'
    balance: false
    checkpoint: false
    verbose: false
    log: false
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    llm_layers: '32'
    C: 0.00001
    pooling: '-1'
    balance: false
    checkpoint: false
    verbose: false
    log: false
node_avg:
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    baseline: node_averaging
    attention_threshold: 0.05
    llm_layers: 'all'
    C: 10
    pooling: 'mean'
    balance: false
    checkpoint: false
    verbose: false
    log: false
edge_avg:
  - 
    seed: 42
    data: "math-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    baseline: edge_averaging
    attention_threshold: 0.05
    llm_layers: 'all'
    C: 100000
    pooling: 'mean'
    balance: false
    checkpoint: false
    verbose: false
    log: false