atp:
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    pooling: 'sum'
    response_only: true
    verbose: false
    log: false
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    pooling: 'sum'
    response_only: false
    verbose: false
    log: false
lc:
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    llm_layers: "23"
    attention_threshold: 0.05
    verbose: false
    log: false
  -
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    llm_layers: "27"
    attention_threshold: 0.05
    verbose: false
    log: false
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    llm_layers: "31"
    attention_threshold: 0.05
    verbose: false
    log: false
lc++:
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    llm_layers: "23"
    attention_threshold: 0.05
    C: 0.01
    balance: false
    verbose: false
    log: false
  -
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    llm_layers: "27"
    attention_threshold: 0.05
    C: 0.01
    balance: false
    verbose: false
    log: false
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    llm_layers: "31"
    attention_threshold: 0.05
    C: 100
    balance: false
    verbose: false
    log: false
lapeig:
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    attention_threshold: 0.05
    topk: 5  # 4 is slightly better, 5 replicates the result from paper, probaly a human mistake, but essentially it is the same result
    verbose: false
    log: false
act:
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    llm_layers: '24'
    C: 100
    pooling: '-2'
    balance: false
    checkpoint: false
    verbose: false
    log: false
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    llm_layers: '28'
    C: 100000
    pooling: '-2'
    balance: false
    checkpoint: false
    verbose: false
    log: false
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    llm_layers: '32'
    C: 0.001
    pooling: '-2'
    balance: false
    checkpoint: false
    verbose: false
    log: false
node_avg:
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    baseline: node_averaging
    attention_threshold: 0.05
    llm_layers: 'all'
    C: 100000
    pooling: 'mean'
    balance: false
    checkpoint: false
    verbose: false
    log: false
edge_avg:
  - 
    seed: 42
    data: "winobias-mistral-7b-i-05__24_28_32_42"
    tokenwise: false
    baseline: edge_averaging
    attention_threshold: 0.05
    llm_layers: 'all'
    C: 100
    pooling: 'mean'
    balance: false
    checkpoint: false
    verbose: false
    log: false